namespace MarktguruApi.Models.Product
{
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// Represents a product in the Marktguru API.
    /// </summary>
    public class Product : IBaseObject
    {
        /// <summary>
        /// Gets or sets the unique identifier for the product.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the product.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the price of the product.
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the product is available.
        /// </summary>
        public bool Available { get; set; }

        /// <summary>
        /// Gets or sets the description of the product.
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the product was created.
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the product was last updated.
        /// </summary>
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets the version of the product.
        /// In a real-world scenario, this would be generated by the database.
        /// </summary>
        public int Version { get; set; }
    }
}